#https://docs.travis-ci.com/user/customizing-the-build/ variaveis
language: android
jdk: oraclejdk8
sudo: false

script: 
    - datahora=`TZ=America/Recife date "+%A %d/%m/%Y %T"`' America/Recife'
    
after_success:
    - chmod +x backend.sh
    - ./backend.sh $GITHUB_PASSHASH_PM $TRAVIS_BRANCH "$datahora"
after_failure:
    - chmod +x backend.sh
    - ./backend.sh $GITHUB_PASSHASH_PM $TRAVIS_BRANCH "$datahora"